spring:
  application:
    name: PLM Migration Assistant
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:plmmigrationassistant;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: ${PORT:8080}
